const GET_ALL = "GET_ALL";
const GET_ALL_FAILURE = "GET_ALL_FAILURE";
const GET_TIPO_VEHICULO = "GET_TIPO_VEHICULO";
const SEARCH_PILOTO = "SEARCH_PPILOTO";
const GET_ALL_PILOTOS = "GET_ALL_PILOTOS";
const APPLY_FILTERS = "APPLY_FILTERS";
const REGISTER_USER = "REGISTER_USER";
const GET_TIPO_VEHICULO_NAME= "GET_TIPO_VEHICULO_NAME";
const GET_INFO_PILOTO = "GET_INFO_PILOTO";
const UPDATE_PILOTO = "UPDATE_PILOTO";
const SOLICITUD_SERVICIO = "SOLICITUD_SERVICIO";
const GET_ALL_CLIENTS = "GET_ALL_CLIENT";
const UPDATE_CLIENT = "UPDATE_CLIENT"
const GET_PILOTOS_TOP = "GET_PILOTOS_TOP"
const SET_USER_SESSION = "SET_USER_SESSION"


export {
  GET_PILOTOS_TOP,
  GET_TIPO_VEHICULO_NAME,
  REGISTER_USER,
  APPLY_FILTERS,
  GET_ALL_PILOTOS,
  SEARCH_PILOTO,
  GET_TIPO_VEHICULO,
  GET_ALL_FAILURE,
  GET_ALL,
  GET_INFO_PILOTO,
  UPDATE_PILOTO,
  SOLICITUD_SERVICIO,
  GET_ALL_CLIENTS,
  UPDATE_CLIENT,
  SET_USER_SESSION
};
